
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';
import type { FixedSizeImage } from './index.js';

/**
 * Auditions
 *
 * Id: 16dea75b-52d3-4f3b-993f-837b1a443c9b
 * Codename: auditions
 */
export type Auditions = CoreContentType<
    AuditionsElementCodenames,
    {
        /**
         * Upcoming auditions description
         *
         * Type: rich_text
         * Required: true
         * Codename: upcoming_auditions_description
         * Id: f6ecb711-72b0-4881-9845-7a17c6f9633a
         */
        readonly upcoming_auditions_description: Elements.RichTextElement<FixedSizeImage>;
        /**
         * Audition date
         *
         * Type: date_time
         * Required: false
         * Codename: audition_date
         * Id: 5d294dba-4b71-4018-b7b3-db248f1e6d43
         */
        readonly audition_date: Elements.DateTimeElement;
        /**
         * Link to audition event
         *
         * Type: text
         * Required: false
         * Codename: link_to_audition_event
         * Id: 832dfc8c-8865-46bc-b2af-7761c4c8f233
         * Guidelines: Such as on Facebook
         */
        readonly link_to_audition_event: Elements.TextElement;
    },
    'auditions'
>;

/**
 * Type representing all available element codenames for Auditions
 */
export type AuditionsElementCodenames = 'upcoming_auditions_description' | 'audition_date' | 'link_to_audition_event';

/**
 * Type guard for Auditions
 *
 * Id: 16dea75b-52d3-4f3b-993f-837b1a443c9b
 * Codename: auditions
 */
export function isAuditions(item: CoreContentType | undefined | null): item is Auditions {
    return item?.system?.type === 'auditions';
}
