
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';
import type { Value } from './index.js';

/**
 * Basic info
 *
 * Id: 0dcc971a-e0dd-4377-87ef-d4dc855554d9
 * Codename: basic_info
 */
export type BasicInfo = CoreContentType<
    BasicInfoElementCodenames,
    {
        /**
         * Name
         *
         * Type: text
         * Required: true
         * Codename: name
         * Id: b7e9d365-0ddd-48d1-8198-0ccdd89d9e90
         */
        readonly name: Elements.TextElement;
        /**
         * Short description
         *
         * Type: text
         * Required: true
         * Codename: short_description
         * Id: 19e4f8be-da91-4e25-9565-8d5eb87a7d8d
         */
        readonly short_description: Elements.TextElement;
        /**
         * About us
         *
         * Type: rich_text
         * Required: true
         * Codename: about_us
         * Id: 3293c565-e20e-4e97-854d-9ae1ac9775d8
         */
        readonly about_us: Elements.RichTextElement<CoreContentType>;
        /**
         * Contact info
         *
         * Type: rich_text
         * Required: true
         * Codename: contact_info
         * Id: a9403a93-a726-4b97-8cb1-fcc0612d3d66
         */
        readonly contact_info: Elements.RichTextElement<CoreContentType>;
        /**
         * Social media
         *
         * Type: text
         * Required: false
         * Codename: social_media
         * Id: 0f52a844-e411-4c52-944d-fc1e5674f281
         * Guidelines: A comma-separated list of social media addresses (e.g., mailto:you@mail.com,https://facebook.com/you)
         */
        readonly social_media: Elements.TextElement;
        /**
         * Logo
         *
         * Type: asset
         * Required: true
         * Codename: logo
         * Id: ce6709e8-e701-487c-ad16-7d39f8c10af7
         */
        readonly logo: Elements.AssetsElement;
        /**
         * Favicon
         *
         * Type: asset
         * Required: true
         * Codename: favicon
         * Id: 1391ef4b-630f-40d9-aa70-04de29efc884
         */
        readonly favicon: Elements.AssetsElement;
        /**
         * Keywords
         *
         * Type: text
         * Required: true
         * Codename: keywords
         * Id: 6e40a72b-ed5b-42e1-9871-446c171a7360
         * Guidelines: For SEO
         */
        readonly keywords: Elements.TextElement;
        /**
         * Values
         *
         * Type: rich_text
         * Required: true
         * Codename: values
         * Id: cc2479ce-84c5-4b1e-ad6f-0fd63beee958
         */
        readonly values: Elements.RichTextElement<Value>;
    },
    'basic_info'
>;

/**
 * Type representing all available element codenames for Basic info
 */
export type BasicInfoElementCodenames =
    | 'name'
    | 'short_description'
    | 'about_us'
    | 'contact_info'
    | 'social_media'
    | 'logo'
    | 'favicon'
    | 'keywords'
    | 'values';

/**
 * Type guard for Basic info
 *
 * Id: 0dcc971a-e0dd-4377-87ef-d4dc855554d9
 * Codename: basic_info
 */
export function isBasicInfo(item: CoreContentType | undefined | null): item is BasicInfo {
    return item?.system?.type === 'basic_info';
}
