import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Basic info
 * Id: 0dcc971a-e0dd-4377-87ef-d4dc855554d9
 * Codename: basic_info
 */
export type BasicInfo = IContentItem<{
    /**
     * About us (rich_text)
     * Required: true
     * Id: 3293c565-e20e-4e97-854d-9ae1ac9775d8
     * Codename: about_us
     */
    about_us: Elements.RichTextElement;

    /**
     * Contact info (rich_text)
     * Required: true
     * Id: a9403a93-a726-4b97-8cb1-fcc0612d3d66
     * Codename: contact_info
     */
    contact_info: Elements.RichTextElement;

    /**
     * Favicon (asset)
     * Required: true
     * Id: 1391ef4b-630f-40d9-aa70-04de29efc884
     * Codename: favicon
     */
    favicon: Elements.AssetsElement;

    /**
     * Keywords (text)
     * Required: true
     * Id: 6e40a72b-ed5b-42e1-9871-446c171a7360
     * Codename: keywords
     *
     * For SEO
     */
    keywords: Elements.TextElement;

    /**
     * Logo (asset)
     * Required: true
     * Id: ce6709e8-e701-487c-ad16-7d39f8c10af7
     * Codename: logo
     */
    logo: Elements.AssetsElement;

    /**
     * Name (text)
     * Required: true
     * Id: b7e9d365-0ddd-48d1-8198-0ccdd89d9e90
     * Codename: name
     */
    name: Elements.TextElement;

    /**
     * Short description (text)
     * Required: true
     * Id: 19e4f8be-da91-4e25-9565-8d5eb87a7d8d
     * Codename: short_description
     */
    short_description: Elements.TextElement;

    /**
     * Social media (text)
     * Required: false
     * Id: 0f52a844-e411-4c52-944d-fc1e5674f281
     * Codename: social_media
     *
     * A comma-separated list of social media addresses (e.g., mailto:you@mail.com,https://facebook.com/you)
     */
    social_media: Elements.TextElement;
}>;
