
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';

/**
 * Call to Action Button
 *
 * Id: 7f62781c-8290-4580-8a34-9dbae5deb7ad
 * Codename: call_to_action_button
 */
export type CallToActionButton = CoreContentType<
    CallToActionButtonElementCodenames,
    {
        /**
         * Button text
         *
         * Type: text
         * Required: true
         * Codename: button_text
         * Id: 681680b9-95a3-4888-b9df-0c9d6b97812e
         * Guidelines: What text people will see
         */
        readonly button_text: Elements.TextElement;
        /**
         * URL
         *
         * Type: text
         * Required: true
         * Codename: url
         * Id: ad6c3f81-50df-4dc4-bf43-009335f06187
         * Guidelines: Where people go after clicking the button
         */
        readonly url: Elements.TextElement;
    },
    'call_to_action_button'
>;

/**
 * Type representing all available element codenames for Call to Action Button
 */
export type CallToActionButtonElementCodenames = 'button_text' | 'url';

/**
 * Type guard for Call to Action Button
 *
 * Id: 7f62781c-8290-4580-8a34-9dbae5deb7ad
 * Codename: call_to_action_button
 */
export function isCallToActionButton(item: CoreContentType | undefined | null): item is CallToActionButton {
    return item?.system?.type === 'call_to_action_button';
}
