
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';

/**
 * Fixed size image
 *
 * Id: 4e396c6b-b785-4b65-9ecf-802707a441ee
 * Codename: fixed_size_image
 */
export type FixedSizeImage = CoreContentType<
    FixedSizeImageElementCodenames,
    {
        /**
         * Height
         *
         * Type: number
         * Required: true
         * Codename: height
         * Id: afe713f9-7237-499b-b2a8-cb8dc3e1f6af
         */
        readonly height: Elements.NumberElement;
        /**
         * Width
         *
         * Type: number
         * Required: true
         * Codename: width
         * Id: 518e08ce-a0b0-4b5e-8801-a2b155c28fa4
         */
        readonly width: Elements.NumberElement;
        /**
         * Image
         *
         * Type: asset
         * Required: true
         * Codename: image
         * Id: 6ed6fb3e-f7f8-4511-94e0-e3659fcc3c23
         */
        readonly image: Elements.AssetsElement;
    },
    'fixed_size_image'
>;

/**
 * Type representing all available element codenames for Fixed size image
 */
export type FixedSizeImageElementCodenames = 'height' | 'width' | 'image';

/**
 * Type guard for Fixed size image
 *
 * Id: 4e396c6b-b785-4b65-9ecf-802707a441ee
 * Codename: fixed_size_image
 */
export function isFixedSizeImage(item: CoreContentType | undefined | null): item is FixedSizeImage {
    return item?.system?.type === 'fixed_size_image';
}
