
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';

/**
 * Image with caption
 *
 * Id: 21a8e9bb-154b-490a-ba51-d2f1ac84ece2
 * Codename: image_with_caption
 */
export type ImageWithCaption = CoreContentType<
    ImageWithCaptionElementCodenames,
    {
        /**
         * Image
         *
         * Type: asset
         * Required: true
         * Codename: image
         * Id: e04882ec-3683-4e88-a5bb-cc599cbb4056
         */
        readonly image: Elements.AssetsElement;
        /**
         * Caption
         *
         * Type: text
         * Required: false
         * Codename: caption
         * Id: 978324a2-369b-4926-86c3-f69af67a2172
         */
        readonly caption: Elements.TextElement;
    },
    'image_with_caption'
>;

/**
 * Type representing all available element codenames for Image with caption
 */
export type ImageWithCaptionElementCodenames = 'image' | 'caption';

/**
 * Type guard for Image with caption
 *
 * Id: 21a8e9bb-154b-490a-ba51-d2f1ac84ece2
 * Codename: image_with_caption
 */
export function isImageWithCaption(item: CoreContentType | undefined | null): item is ImageWithCaption {
    return item?.system?.type === 'image_with_caption';
}
