
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';
import type { Season } from './index.js';

/**
 * Past shows
 *
 * Id: c48c90f0-0e97-4955-b9b7-25a9989cfb75
 * Codename: past_shows
 */
export type PastShows = CoreContentType<
    PastShowsElementCodenames,
    {
        /**
         * Seasons
         *
         * Type: modular_content
         * Required: true
         * Codename: seasons
         * Id: ceff5def-6232-4020-ba62-d27e76cb8fbb
         */
        readonly seasons: Elements.LinkedItemsElement<Season>;
    },
    'past_shows'
>;

/**
 * Type representing all available element codenames for Past shows
 */
export type PastShowsElementCodenames = 'seasons';

/**
 * Type guard for Past shows
 *
 * Id: c48c90f0-0e97-4955-b9b7-25a9989cfb75
 * Codename: past_shows
 */
export function isPastShows(item: CoreContentType | undefined | null): item is PastShows {
    return item?.system?.type === 'past_shows';
}
