import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Season } from './season.js';

/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Past shows
 * Id: c48c90f0-0e97-4955-b9b7-25a9989cfb75
 * Codename: past_shows
 */
export type PastShows = IContentItem<{
    /**
     * Seasons (modular_content)
     * Required: true
     * Id: ceff5def-6232-4020-ba62-d27e76cb8fbb
     * Codename: seasons
     */
    seasons: Elements.LinkedItemsElement<Season>;
}>;
