
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';
import type { Show } from './index.js';

/**
 * Season
 *
 * Id: 570b0342-b2c5-456d-a742-d4cb5bee2516
 * Codename: season
 */
export type Season = CoreContentType<
    SeasonElementCodenames,
    {
        /**
         * Season Start Year
         *
         * Type: number
         * Required: true
         * Codename: season_start_year
         * Id: 5cb89261-7f4e-4dfd-9df2-f50c735f123f
         * Guidelines: The year the season started
         */
        readonly season_start_year: Elements.NumberElement;
        /**
         * Season End Year
         *
         * Type: number
         * Required: true
         * Codename: season_end_year
         * Id: e333bd56-d9fc-40f1-b8ca-c8a0c1e07e53
         * Guidelines: The year the season ended
         */
        readonly season_end_year: Elements.NumberElement;
        /**
         * Season name
         *
         * Type: text
         * Required: true
         * Codename: season_name
         * Id: 008bc8b6-f1a3-492f-95a1-3d394e85bdf7
         */
        readonly season_name: Elements.TextElement;
        /**
         * Shows
         *
         * Type: modular_content
         * Required: true
         * Codename: shows
         * Id: dc1f14f2-6f21-4a0a-aff3-4adbf61a34a2
         * Guidelines: All the shows that were part of the season
         */
        readonly shows: Elements.LinkedItemsElement<Show>;
    },
    'season'
>;

/**
 * Type representing all available element codenames for Season
 */
export type SeasonElementCodenames = 'season_start_year' | 'season_end_year' | 'season_name' | 'shows';

/**
 * Type guard for Season
 *
 * Id: 570b0342-b2c5-456d-a742-d4cb5bee2516
 * Codename: season
 */
export function isSeason(item: CoreContentType | undefined | null): item is Season {
    return item?.system?.type === 'season';
}
