import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type Show } from './show.js';

/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Season
 * Id: 570b0342-b2c5-456d-a742-d4cb5bee2516
 * Codename: season
 */
export type Season = IContentItem<{
    /**
     * Season End Year (number)
     * Required: true
     * Id: e333bd56-d9fc-40f1-b8ca-c8a0c1e07e53
     * Codename: season_end_year
     *
     * The year the season ended
     */
    season_end_year: Elements.NumberElement;

    /**
     * Season name (text)
     * Required: true
     * Id: 008bc8b6-f1a3-492f-95a1-3d394e85bdf7
     * Codename: season_name
     */
    season_name: Elements.TextElement;

    /**
     * Season Start Year (number)
     * Required: true
     * Id: 5cb89261-7f4e-4dfd-9df2-f50c735f123f
     * Codename: season_start_year
     *
     * The year the season started
     */
    season_start_year: Elements.NumberElement;

    /**
     * Shows (modular_content)
     * Required: true
     * Id: dc1f14f2-6f21-4a0a-aff3-4adbf61a34a2
     * Codename: shows
     *
     * All the shows that were part of the season
     */
    shows: Elements.LinkedItemsElement<Show>;
}>;
