import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.1'
 *
 * Show
 * Codename: show
 */
export type Show = IContentItem<{
  /**
   * Description (rich_text)
   * Required: true
   * Codename: description
   */
  description: Elements.RichTextElement;

  /**
   * Gallery (asset)
   * Required: false
   * Codename: gallery
   *
   * Various images from the show displayed as a gallery
   */
  gallery: Elements.AssetsElement;

  /**
   * Main image (asset)
   * Required: true
   * Codename: main_image
   *
   * A single image to be used as a preview
   */
  main_image: Elements.AssetsElement;

  /**
   * Name (text)
   * Required: true
   * Codename: name
   */
  name: Elements.TextElement;

  /**
   * Premiere (date_time)
   * Required: false
   * Codename: premiere
   */
  premiere: Elements.DateTimeElement;

  /**
   * Short description (text)
   * Required: true
   * Codename: short_description
   */
  short_description: Elements.TextElement;

  /**
   * Ticket link (text)
   * Required: false
   * Codename: ticket_link
   *
   * The URL where tickets are sold
   */
  ticket_link: Elements.TextElement;

  /**
   * URL (url_slug)
   * Required: true
   * Codename: url
   */
  url: Elements.UrlSlugElement;
}>;
