
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.js';
import type { FixedSizeImage, CallToActionButton, ImageWithCaption } from './index.js';

/**
 * Show
 *
 * Id: e9c110a9-7a96-47bb-922d-397ef9632c51
 * Codename: show
 */
export type Show = CoreContentType<
    ShowElementCodenames,
    {
        /**
         * Name
         *
         * Type: text
         * Required: true
         * Codename: name
         * Id: 62be8611-be31-4983-a51b-d99cbde75972
         */
        readonly name: Elements.TextElement;
        /**
         * Main image
         *
         * Type: asset
         * Required: true
         * Codename: main_image
         * Id: 3ee38568-bde5-428d-9702-bf646c7d7547
         * Guidelines: A single image to be used as a preview
         */
        readonly main_image: Elements.AssetsElement;
        /**
         * Short description
         *
         * Type: text
         * Required: true
         * Codename: short_description
         * Id: 0c2ac722-9302-4d59-8977-a00414844843
         */
        readonly short_description: Elements.TextElement;
        /**
         * Description
         *
         * Type: rich_text
         * Required: true
         * Codename: description
         * Id: 9e6ba8a8-a878-4c56-a7e7-5dcf055de610
         */
        readonly description: Elements.RichTextElement<FixedSizeImage | CallToActionButton>;
        /**
         * Premiere
         *
         * Type: date_time
         * Required: false
         * Codename: premiere
         * Id: 9e1ed95e-3b15-43b9-845a-fc8d02adc4b8
         */
        readonly premiere: Elements.DateTimeElement;
        /**
         * Ticket link
         *
         * Type: text
         * Required: false
         * Codename: ticket_link
         * Id: 7a35d9c3-a52e-435b-ab65-95e453e2f8ff
         * Guidelines: The URL where tickets are sold
         */
        readonly ticket_link: Elements.TextElement;
        /**
         * Full performance link
         *
         * Type: text
         * Required: false
         * Codename: full_performance_link
         * Id: 541da3ef-4032-430b-a839-c8a3eda6d4a9
         * Guidelines: A link to the full performance of the show
         */
        readonly full_performance_link: Elements.TextElement;
        /**
         * Gallery
         *
         * Type: asset
         * Required: false
         * Codename: gallery
         * Id: 6f0583db-9d1f-4caa-af8a-e36c0ee505c1
         * Guidelines: Various images from the show displayed as a gallery
         */
        readonly gallery: Elements.AssetsElement;
        /**
         * Gallery with captions
         *
         * Type: rich_text
         * Required: false
         * Codename: gallery_with_captions
         * Id: 92fe8244-d346-4411-820c-f5f86e4ac666
         * Guidelines: Include images with a caption to be displayed in a scrolling gallery
         */
        readonly gallery_with_captions: Elements.RichTextElement<ImageWithCaption>;
        /**
         * URL
         *
         * Type: url_slug
         * Required: true
         * Codename: url
         * Id: ff17c8ed-31d6-48e3-beac-fa0ab3045fe7
         */
        readonly url: Elements.UrlSlugElement;
    },
    'show'
>;

/**
 * Type representing all available element codenames for Show
 */
export type ShowElementCodenames =
    | 'name'
    | 'main_image'
    | 'short_description'
    | 'description'
    | 'premiere'
    | 'ticket_link'
    | 'full_performance_link'
    | 'gallery'
    | 'gallery_with_captions'
    | 'url';

/**
 * Type guard for Show
 *
 * Id: e9c110a9-7a96-47bb-922d-397ef9632c51
 * Codename: show
 */
export function isShow(item: CoreContentType | undefined | null): item is Show {
    return item?.system?.type === 'show';
}
