
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CallToActionButton, FixedSizeImage, ImageWithCaption } from './index.js';
import type { CoreContentType } from '../system/index.js';

/**
 * Value
 *
 * Id: eb8249ce-99d3-49f9-950c-9fbd5b4d4aa4
 * Codename: value
 */
export type Value = CoreContentType<
    ValueElementCodenames,
    {
        /**
         * Name
         *
         * Type: text
         * Required: true
         * Codename: name
         * Id: 4efac830-7c33-4859-9359-10d83195d06f
         */
        readonly name: Elements.TextElement;
        /**
         * Icon
         *
         * Type: text
         * Required: false
         * Codename: icon
         * Id: b1cd0a4c-9cab-4ee7-b706-e69b7758cf8f
         * Guidelines: A material design icon to describe the value. Use camel case starting with "mdi".
         */
        readonly icon: Elements.TextElement;
        /**
         * Description
         *
         * Type: rich_text
         * Required: true
         * Codename: description
         * Id: 18a90a02-36a1-498a-9748-dfac664bb5e7
         */
        readonly description: Elements.RichTextElement<CallToActionButton | FixedSizeImage | ImageWithCaption>;
    },
    'value'
>;

/**
 * Type representing all available element codenames for Value
 */
export type ValueElementCodenames = 'name' | 'icon' | 'description';

/**
 * Type guard for Value
 *
 * Id: eb8249ce-99d3-49f9-950c-9fbd5b4d4aa4
 * Codename: value
 */
export function isValue(item: CoreContentType | undefined | null): item is Value {
    return item?.system?.type === 'value';
}
