/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { CollectionCodenames } from '../system/collections.generated.js';
           
            /*
* Type representing codename of 'Default' collection
*/
            export type DefaultCollectionCodename = keyof Pick<Record<CollectionCodenames, null>, "default">;

            /*
* Typeguard for codename of 'Default' collection
*/
            export function isDefaultCollectionCodename(value: string | undefined | null): value is DefaultCollectionCodename {
                return typeof value === 'string' && value === ('default' satisfies DefaultCollectionCodename);
            }
            