
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.1.2'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Czech Theater
* Environment: Production
* Id: fb599585-baec-0077-1624-981d3321fff0
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = 'en-US';

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
    | 'auditions'
    | 'basic_info'
    | 'call_to_action_button'
    | 'fixed_size_image'
    | 'future_shows'
    | 'image_with_caption'
    | 'past_shows'
    | 'season'
    | 'show'
    | 'theater_fact'
    | 'value';

/**
 * Type representing all collections
 */
export type CollectionCodenames = 'default';

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = 'default';

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames = never;

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames = 'archived' | 'draft' | 'published' | 'scheduled';

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
    | 'about_us'
    | 'audition_date'
    | 'button_text'
    | 'caption'
    | 'contact_info'
    | 'description'
    | 'favicon'
    | 'full_performance_link'
    | 'gallery_with_captions'
    | 'gallery'
    | 'height'
    | 'icon'
    | 'image'
    | 'keywords'
    | 'link_to_audition_event'
    | 'logo'
    | 'main_image'
    | 'name'
    | 'premiere'
    | 'season_end_year'
    | 'season_name'
    | 'season_start_year'
    | 'seasons'
    | 'short_description'
    | 'shows'
    | 'social_media'
    | 'ticket_link'
    | 'upcoming_auditions_description'
    | 'url'
    | 'values'
    | 'width';
