/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all element codenames
*/
            export const elementCodenames = ['shows', 'season_start_year', 'season_end_year', 'season_name', 'name', 'icon', 'description', 'height', 'width', 'image', 'short_description', 'about_us', 'contact_info', 'social_media', 'logo', 'favicon', 'keywords', 'values', 'seasons', 'upcoming_auditions_description', 'audition_date', 'link_to_audition_event', 'button_text', 'url', 'main_image', 'trailer', 'premiere', 'ticket_link', 'full_performance_link', 'gallery', 'gallery_with_captions', 'trailer_video', 'trailer_video_small', 'link_to_video_hosted_elsewhere', 'caption'] as const;;
           
            /*
* Type representing all element codenames
*/
            export type ElementCodenames = typeof elementCodenames[number];;

            /*
* Typeguard for element codename
*/
            export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
                return typeof value === 'string' && (elementCodenames as readonly string[]).includes(value);
            };