/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            
            /*
* Array of all snippet codenames
*/
            export const snippetCodenames = [] as const;;
           
            /*
* Type representing all snippet codenames
*/
            export type SnippetCodenames = typeof snippetCodenames[number];;

            /*
* Typeguard for snippet codename
*/
            export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
                return typeof value === 'string' && (snippetCodenames as readonly string[]).includes(value);
            };