/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { LanguageCodenames } from '../system/languages.generated.js';
           
            /*
* Type representing codename of 'English' language
*/
            export type EnglishLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "en-US">;

            /*
* Typeguard for codename of 'English' language
*/
            export function isEnglishLanguageCodename(value: string | undefined | null): value is EnglishLanguageCodename {
                return typeof value === 'string' && value === ('en-US' satisfies EnglishLanguageCodename);
            }
            