name: Lint
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: './.github/shared/setup-node'

        # This step needs to go before linting to generate the types
        # Including the environment variable ensures the type is generated
      - name: Check
        run: PUBLIC_KONTENT_ENVIRONMENT_ID=test npm run check
      - name: Lint
        run: npm run lint
