name: Lint
on:
  push:
    branches-ignore:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/shared/setup-node'

        # This step needs to go before linting to generate the types
        # Including the environment variable ensures the type is generated
      - name: Check
        run: >
          PUBLIC_KONTENT_PREVIEW=""
          PUBLIC_KONTENT_PREVIEW_API_KEY=abc
          PUBLIC_KONTENT_ENVIRONMENT_ID=test npm run check
      - name: Lint
        run: pnpm lint
