name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUBLIC_KONTENT_ENVIRONMENT_ID: ${{ vars.PUBLIC_KONTENT_ENVIRONMENT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/shared/setup-node'
      #- name: Test
      #  run: npm test
      #- name: Coverage
      #  uses: paambaati/codeclimate-action@v3.2.0
      #  env:
      #    CC_TEST_REPORTER_ID: 12e45f7dc77e1f2aea24b7516aa3a069f14424da47e53403022698626881b0ab
      #  with:
      #    coverageCommand: npm run test:coverage
      - name: Build
        run: npm run build
