name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUBLIC_KONTENT_ENVIRONMENT_ID: ${{ vars.PUBLIC_KONTENT_ENVIRONMENT_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/shared/setup-node'
      - name: Fix export
        run: jq '.exports.".".default = "./dist/index.js"' ./node_modules/@portabletext/svelte/package.json > test.json && mv test.json ./node_modules/@portabletext/svelte/package.json
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
      - name: Coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 12e45f7dc77e1f2aea24b7516aa3a069f14424da47e53403022698626881b0ab
        with:
          coverageCommand: pnpm test:coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
