/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CallToActionButtonType } from '../types/call-to-action-button-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { FixedSizeImageType } from '../types/fixed-size-image-type.generated.js';
import type { ImageWithCaptionType } from '../types/image-with-caption-type.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { TrailerType } from '../types/trailer-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of '2 Column Layout' type
*/
            export type _2ColumnLayoutTypeCodename = keyof Pick<Record<TypeCodenames, null>, "n2_column_layout">;

            /*
* Typeguard for codename of '2 Column Layout' type
*/
            export function is_2ColumnLayoutTypeCodename(value: string | undefined | null): value is _2ColumnLayoutTypeCodename {
                return typeof value === 'string' && value === ('n2_column_layout' satisfies _2ColumnLayoutTypeCodename);
            }

/*
    * 2 Column Layout
    *
    * Id: 9bb59bcb-7da3-47d2-af75-e07487f69675
* Codename: n2_column_layout
    */
export type _2ColumnLayoutType = IContentItem<
{
/*
    * Left side
    *
    * Codename: left_side
* Id: 2bc632bb-09fb-4d5e-a101-ce6f0cb0ebe9
* Type: rich_text
* Required: true
* Allowed content types: fixed_size_image, call_to_action_button, trailer, image_with_caption
    */
                readonly left_side: Elements.RichTextElement<FixedSizeImageType | CallToActionButtonType | TrailerType | ImageWithCaptionType>;

/*
    * Right side
    *
    * Codename: right_side
* Id: 75781aab-769f-4748-b79d-94cebcf14427
* Type: rich_text
* Required: true
* Allowed content types: trailer, fixed_size_image, call_to_action_button, image_with_caption
    */
                readonly right_side: Elements.RichTextElement<TrailerType | FixedSizeImageType | CallToActionButtonType | ImageWithCaptionType>;}, 
_2ColumnLayoutTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for 2 Column Layout
*/
export type _2ColumnLayoutTypeElementCodenames = 'left_side' | 'right_side';;

/*
    * Type guard for 2 Column Layout
    *
    * Id: 9bb59bcb-7da3-47d2-af75-e07487f69675
* Codename: n2_column_layout
    */
export function is_2ColumnLayoutType(item: IContentItem | undefined | null): item is _2ColumnLayoutType {
                return item?.system.type === ('n2_column_layout' satisfies _2ColumnLayoutTypeCodename);
            };



            