/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { ValueType } from '../types/value-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Basic info' type
*/
            export type BasicInfoTypeCodename = keyof Pick<Record<TypeCodenames, null>, "basic_info">;

            /*
* Typeguard for codename of 'Basic info' type
*/
            export function isBasicInfoTypeCodename(value: string | undefined | null): value is BasicInfoTypeCodename {
                return typeof value === 'string' && value === ('basic_info' satisfies BasicInfoTypeCodename);
            }

/*
    * Basic info
    *
    * Id: 0dcc971a-e0dd-4377-87ef-d4dc855554d9
* Codename: basic_info
    */
export type BasicInfoType = IContentItem<
{
/*
    * Name
    *
    * Codename: name
* Id: b7e9d365-0ddd-48d1-8198-0ccdd89d9e90
* Type: text
* Required: true
    */
                readonly name: Elements.TextElement;

/*
    * Short description
    *
    * Codename: short_description
* Id: 19e4f8be-da91-4e25-9565-8d5eb87a7d8d
* Type: text
* Required: true
    */
                readonly short_description: Elements.TextElement;

/*
    * About us
    *
    * Codename: about_us
* Id: 3293c565-e20e-4e97-854d-9ae1ac9775d8
* Type: rich_text
* Required: true
    */
                readonly about_us: Elements.RichTextElement<CoreType>;

/*
    * Contact info
    *
    * Codename: contact_info
* Id: a9403a93-a726-4b97-8cb1-fcc0612d3d66
* Type: rich_text
* Required: true
    */
                readonly contact_info: Elements.RichTextElement<CoreType>;

/*
    * Social media
    *
    * Codename: social_media
* Id: 0f52a844-e411-4c52-944d-fc1e5674f281
* Type: text
* Required: false
* Guidelines: A comma-separated list of social media addresses (e.g., mailto:you@mail.com,https://facebook.com/you)
    */
                readonly social_media: Elements.TextElement;

/*
    * Logo
    *
    * Codename: logo
* Id: ce6709e8-e701-487c-ad16-7d39f8c10af7
* Type: asset
* Required: true
    */
                readonly logo: Elements.AssetsElement;

/*
    * Favicon
    *
    * Codename: favicon
* Id: 1391ef4b-630f-40d9-aa70-04de29efc884
* Type: asset
* Required: true
    */
                readonly favicon: Elements.AssetsElement;

/*
    * Keywords
    *
    * Codename: keywords
* Id: 6e40a72b-ed5b-42e1-9871-446c171a7360
* Type: text
* Required: true
* Guidelines: For SEO
    */
                readonly keywords: Elements.TextElement;

/*
    * Values
    *
    * Codename: values
* Id: cc2479ce-84c5-4b1e-ad6f-0fd63beee958
* Type: rich_text
* Required: true
* Allowed content types: value
    */
                readonly values: Elements.RichTextElement<ValueType>;}, 
BasicInfoTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Basic info
*/
export type BasicInfoTypeElementCodenames = 'name' | 'short_description' | 'about_us' | 'contact_info' | 'social_media' | 'logo' | 'favicon' | 'keywords' | 'values';;

/*
    * Type guard for Basic info
    *
    * Id: 0dcc971a-e0dd-4377-87ef-d4dc855554d9
* Codename: basic_info
    */
export function isBasicInfoType(item: IContentItem | undefined | null): item is BasicInfoType {
                return item?.system.type === ('basic_info' satisfies BasicInfoTypeCodename);
            };



            