/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Fixed size image' type
*/
            export type FixedSizeImageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "fixed_size_image">;

            /*
* Typeguard for codename of 'Fixed size image' type
*/
            export function isFixedSizeImageTypeCodename(value: string | undefined | null): value is FixedSizeImageTypeCodename {
                return typeof value === 'string' && value === ('fixed_size_image' satisfies FixedSizeImageTypeCodename);
            }

/*
    * Fixed size image
    *
    * Id: 4e396c6b-b785-4b65-9ecf-802707a441ee
* Codename: fixed_size_image
    */
export type FixedSizeImageType = IContentItem<
{
/*
    * Height
    *
    * Codename: height
* Id: afe713f9-7237-499b-b2a8-cb8dc3e1f6af
* Type: number
* Required: true
    */
                readonly height: Elements.NumberElement;

/*
    * Width
    *
    * Codename: width
* Id: 518e08ce-a0b0-4b5e-8801-a2b155c28fa4
* Type: number
* Required: true
    */
                readonly width: Elements.NumberElement;

/*
    * Image
    *
    * Codename: image
* Id: 6ed6fb3e-f7f8-4511-94e0-e3659fcc3c23
* Type: asset
* Required: true
    */
                readonly image: Elements.AssetsElement;}, 
FixedSizeImageTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Fixed size image
*/
export type FixedSizeImageTypeElementCodenames = 'height' | 'width' | 'image';;

/*
    * Type guard for Fixed size image
    *
    * Id: 4e396c6b-b785-4b65-9ecf-802707a441ee
* Codename: fixed_size_image
    */
export function isFixedSizeImageType(item: IContentItem | undefined | null): item is FixedSizeImageType {
                return item?.system.type === ('fixed_size_image' satisfies FixedSizeImageTypeCodename);
            };



            