/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Image with caption' type
*/
            export type ImageWithCaptionTypeCodename = keyof Pick<Record<TypeCodenames, null>, "image_with_caption">;

            /*
* Typeguard for codename of 'Image with caption' type
*/
            export function isImageWithCaptionTypeCodename(value: string | undefined | null): value is ImageWithCaptionTypeCodename {
                return typeof value === 'string' && value === ('image_with_caption' satisfies ImageWithCaptionTypeCodename);
            }

/*
    * Image with caption
    *
    * Id: 21a8e9bb-154b-490a-ba51-d2f1ac84ece2
* Codename: image_with_caption
    */
export type ImageWithCaptionType = IContentItem<
{
/*
    * Image
    *
    * Codename: image
* Id: e04882ec-3683-4e88-a5bb-cc599cbb4056
* Type: asset
* Required: true
    */
                readonly image: Elements.AssetsElement;

/*
    * Caption
    *
    * Codename: caption
* Id: 978324a2-369b-4926-86c3-f69af67a2172
* Type: text
* Required: false
    */
                readonly caption: Elements.TextElement;}, 
ImageWithCaptionTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Image with caption
*/
export type ImageWithCaptionTypeElementCodenames = 'image' | 'caption';;

/*
    * Type guard for Image with caption
    *
    * Id: 21a8e9bb-154b-490a-ba51-d2f1ac84ece2
* Codename: image_with_caption
    */
export function isImageWithCaptionType(item: IContentItem | undefined | null): item is ImageWithCaptionType {
                return item?.system.type === ('image_with_caption' satisfies ImageWithCaptionTypeCodename);
            };



            