/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CallToActionButtonType } from '../types/call-to-action-button-type.generated.js';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { FixedSizeImageType } from '../types/fixed-size-image-type.generated.js';
import type { ImageWithCaptionType } from '../types/image-with-caption-type.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { TheaterFactType } from '../types/theater-fact-type.generated.js';
import type { TrailerType } from '../types/trailer-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Newsletter' type
*/
            export type NewsletterTypeCodename = keyof Pick<Record<TypeCodenames, null>, "newsletter">;

            /*
* Typeguard for codename of 'Newsletter' type
*/
            export function isNewsletterTypeCodename(value: string | undefined | null): value is NewsletterTypeCodename {
                return typeof value === 'string' && value === ('newsletter' satisfies NewsletterTypeCodename);
            }

/*
    * Newsletter
    *
    * Id: a5f9b36b-e1d3-47c0-a4cb-880b57221dd2
* Codename: newsletter
    */
export type NewsletterType = IContentItem<
{
/*
    * Month and Year
    *
    * Codename: month_and_year
* Id: d28af8e7-c279-47d8-91ad-468e454dcd41
* Type: text
* Required: true
* Guidelines: Write it as in this example: "November 2025"
    */
                readonly month_and_year: Elements.TextElement;

/*
    * Slug
    *
    * Codename: slug
* Id: 85b9e515-4189-46b9-9af9-96b02ca54d99
* Type: url_slug
* Required: true
* Guidelines: Write as month-year, as in this example: "november-2025"
    */
                readonly slug: Elements.UrlSlugElement;

/*
    * Introduction
    *
    * Codename: introduction
* Id: 9175bb7a-2c2c-412e-840e-85b121063b74
* Type: rich_text
* Required: true
* Allowed content types: image_with_caption, fixed_size_image, call_to_action_button, trailer
    */
                readonly introduction: Elements.RichTextElement<ImageWithCaptionType | FixedSizeImageType | CallToActionButtonType | TrailerType>;

/*
    * Upcoming shows
    *
    * Codename: upcoming_shows
* Id: 46ed914d-21f1-400b-88fe-8e82ecdd0274
* Type: rich_text
* Required: true
* Allowed content types: call_to_action_button, fixed_size_image, image_with_caption, trailer
    */
                readonly upcoming_shows: Elements.RichTextElement<CallToActionButtonType | FixedSizeImageType | ImageWithCaptionType | TrailerType>;

/*
    * Notes from production
    *
    * Codename: notes_from_production
* Id: 60a72c7d-7dd1-4ba9-b9f3-d1959bfd85cc
* Type: rich_text
* Required: true
* Allowed content types: fixed_size_image, call_to_action_button, image_with_caption, trailer
    */
                readonly notes_from_production: Elements.RichTextElement<FixedSizeImageType | CallToActionButtonType | ImageWithCaptionType | TrailerType>;

/*
    * Intermission
    *
    * Codename: intermission
* Id: e95c4cb8-26a1-4081-9116-b610faa7ce5e
* Type: modular_content
* Required: true
* Allowed content types: theater_fact
    */
                readonly intermission: Elements.LinkedItemsElement<TheaterFactType>;

/*
    * Interview
    *
    * Codename: interview
* Id: c45120f9-f85f-4af6-bd8c-14e15eae17f2
* Type: rich_text
* Required: true
* Allowed content types: call_to_action_button, fixed_size_image, image_with_caption
    */
                readonly interview: Elements.RichTextElement<CallToActionButtonType | FixedSizeImageType | ImageWithCaptionType>;

/*
    * Past play
    *
    * Codename: past_play
* Id: 1848a3f7-daa8-424d-91d4-2cb70c376877
* Type: rich_text
* Required: true
* Allowed content types: call_to_action_button, fixed_size_image, image_with_caption
    */
                readonly past_play: Elements.RichTextElement<CallToActionButtonType | FixedSizeImageType | ImageWithCaptionType>;}, 
NewsletterTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Newsletter
*/
export type NewsletterTypeElementCodenames = 'month_and_year' | 'slug' | 'introduction' | 'upcoming_shows' | 'notes_from_production' | 'intermission' | 'interview' | 'past_play';;

/*
    * Type guard for Newsletter
    *
    * Id: a5f9b36b-e1d3-47c0-a4cb-880b57221dd2
* Codename: newsletter
    */
export function isNewsletterType(item: IContentItem | undefined | null): item is NewsletterType {
                return item?.system.type === ('newsletter' satisfies NewsletterTypeCodename);
            };



            