/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { SeasonType } from '../types/season-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Past shows' type
*/
            export type PastShowsTypeCodename = keyof Pick<Record<TypeCodenames, null>, "past_shows">;

            /*
* Typeguard for codename of 'Past shows' type
*/
            export function isPastShowsTypeCodename(value: string | undefined | null): value is PastShowsTypeCodename {
                return typeof value === 'string' && value === ('past_shows' satisfies PastShowsTypeCodename);
            }

/*
    * Past shows
    *
    * Id: c48c90f0-0e97-4955-b9b7-25a9989cfb75
* Codename: past_shows
    */
export type PastShowsType = IContentItem<
{
/*
    * Seasons
    *
    * Codename: seasons
* Id: ceff5def-6232-4020-ba62-d27e76cb8fbb
* Type: modular_content
* Required: true
* Allowed content types: season
    */
                readonly seasons: Elements.LinkedItemsElement<SeasonType>;}, 
PastShowsTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Past shows
*/
export type PastShowsTypeElementCodenames = 'seasons';;

/*
    * Type guard for Past shows
    *
    * Id: c48c90f0-0e97-4955-b9b7-25a9989cfb75
* Codename: past_shows
    */
export function isPastShowsType(item: IContentItem | undefined | null): item is PastShowsType {
                return item?.system.type === ('past_shows' satisfies PastShowsTypeCodename);
            };



            