/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { ShowType } from '../types/show-type.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Season' type
*/
            export type SeasonTypeCodename = keyof Pick<Record<TypeCodenames, null>, "season">;

            /*
* Typeguard for codename of 'Season' type
*/
            export function isSeasonTypeCodename(value: string | undefined | null): value is SeasonTypeCodename {
                return typeof value === 'string' && value === ('season' satisfies SeasonTypeCodename);
            }

/*
    * Season
    *
    * Id: 570b0342-b2c5-456d-a742-d4cb5bee2516
* Codename: season
    */
export type SeasonType = IContentItem<
{
/*
    * Season Start Year
    *
    * Codename: season_start_year
* Id: 5cb89261-7f4e-4dfd-9df2-f50c735f123f
* Type: number
* Required: true
* Guidelines: The year the season started
    */
                readonly season_start_year: Elements.NumberElement;

/*
    * Season End Year
    *
    * Codename: season_end_year
* Id: e333bd56-d9fc-40f1-b8ca-c8a0c1e07e53
* Type: number
* Required: true
* Guidelines: The year the season ended
    */
                readonly season_end_year: Elements.NumberElement;

/*
    * Season name
    *
    * Codename: season_name
* Id: 008bc8b6-f1a3-492f-95a1-3d394e85bdf7
* Type: text
* Required: true
    */
                readonly season_name: Elements.TextElement;

/*
    * Shows
    *
    * Codename: shows
* Id: dc1f14f2-6f21-4a0a-aff3-4adbf61a34a2
* Type: modular_content
* Required: true
* Allowed content types: show
* Guidelines: All the shows that were part of the season
    */
                readonly shows: Elements.LinkedItemsElement<ShowType>;}, 
SeasonTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Season
*/
export type SeasonTypeElementCodenames = 'season_start_year' | 'season_end_year' | 'season_name' | 'shows';;

/*
    * Type guard for Season
    *
    * Id: 570b0342-b2c5-456d-a742-d4cb5bee2516
* Codename: season
    */
export function isSeasonType(item: IContentItem | undefined | null): item is SeasonType {
                return item?.system.type === ('season' satisfies SeasonTypeCodename);
            };



            