/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Czech Theater
 * Environment: Production
 * Id: fb599585-baec-0077-1624-981d3321fff0
 * 
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.js';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.js';
import type { CoreType } from '../system/types.generated.js';
import type { LanguageCodenames } from '../system/languages.generated.js';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.js';
           
            /*
* Type representing codename of 'Theater fact' type
*/
            export type TheaterFactTypeCodename = keyof Pick<Record<TypeCodenames, null>, "theater_fact">;

            /*
* Typeguard for codename of 'Theater fact' type
*/
            export function isTheaterFactTypeCodename(value: string | undefined | null): value is TheaterFactTypeCodename {
                return typeof value === 'string' && value === ('theater_fact' satisfies TheaterFactTypeCodename);
            }

/*
    * Theater fact
    *
    * Id: 7ab02166-03c6-4491-b095-61ffca6f0c20
* Codename: theater_fact
    */
export type TheaterFactType = IContentItem<
{
/*
    * Description
    *
    * Codename: description
* Id: 56cf0d02-f9f3-4696-bddd-4549b9db7961
* Type: rich_text
* Required: false
    */
                readonly description: Elements.RichTextElement<CoreType>;

/*
    * Image
    *
    * Codename: image
* Id: 63ee712a-1202-4446-9b1c-51dedab57161
* Type: asset
* Required: false
    */
                readonly image: Elements.AssetsElement;}, 
TheaterFactTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Theater fact
*/
export type TheaterFactTypeElementCodenames = 'description' | 'image';;

/*
    * Type guard for Theater fact
    *
    * Id: 7ab02166-03c6-4491-b095-61ffca6f0c20
* Codename: theater_fact
    */
export function isTheaterFactType(item: IContentItem | undefined | null): item is TheaterFactType {
                return item?.system.type === ('theater_fact' satisfies TheaterFactTypeCodename);
            };



            